version: '2'
networks:
    ghost:
services:
    ghost-app:
        build: ghost
        networks:
            - ghost
        depends_on:
            - db
        ports:
            - "2368:2368"
    nginx:
        build: nginx
        networks:
            - ghost
        depends_on:
            - ghost-app
        ports:
            - "8080:80"
    db:
        image: "mysql:5.7.15" 
        networks:
            - ghost
        environment:
            MYSQL_ROOT_PASSWORD: mysql_root
            MYSQL_USER: ghost
            MYSQL_PASSWORD: ghost
        volumes:
            - D:\Docker\dockerfile\compose\dbdata:/var/lib/mysql
        ports:
            - "3336:3336"